if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

set shell=sh
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ctrlpvim/ctrlp.vim'	
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'wellle/visual-split.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

source ../coc/cocrc


let g:ale_lint_on_text_changed = 'always'
highlight ALEErrorSign ctermbg=NONE ctermfg=red
highlight ALEWarningSign ctermbg=NONE ctermfg=yellow


if executable('rg')
  let g:ctrlp_user_command = 'rg %s --files --hidden --color=never --glob ""'
endif

set splitbelow
set splitright
set suffixesadd+=.js

map <silent> <C-b> :NERDTreeToggle<CR>

